/**
 * UX Research Study Tracker API
 * API for managing UX research studies
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UxResearchStudyTrackerApi);
  }
}(this, function(expect, UxResearchStudyTrackerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UxResearchStudyTrackerApi.StudyCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StudyCreate', function() {
    it('should create an instance of StudyCreate', function() {
      // uncomment below and update the code to test StudyCreate
      //var instance = new UxResearchStudyTrackerApi.StudyCreate();
      //expect(instance).to.be.a(UxResearchStudyTrackerApi.StudyCreate);
    });

    it('should have the property studyTitle (base name: "studyTitle")', function() {
      // uncomment below and update the code to test the property studyTitle
      //var instance = new UxResearchStudyTrackerApi.StudyCreate();
      //expect(instance).to.be();
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new UxResearchStudyTrackerApi.StudyCreate();
      //expect(instance).to.be();
    });

    it('should have the property participants (base name: "participants")', function() {
      // uncomment below and update the code to test the property participants
      //var instance = new UxResearchStudyTrackerApi.StudyCreate();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new UxResearchStudyTrackerApi.StudyCreate();
      //expect(instance).to.be();
    });

  });

}));
