/**
 * UX Research Study Tracker API
 * API for managing UX research studies
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StudyUpdate model module.
 * @module model/StudyUpdate
 * @version 1.0.0
 */
class StudyUpdate {
    /**
     * Constructs a new <code>StudyUpdate</code>.
     * @alias module:model/StudyUpdate
     */
    constructor() { 
        
        StudyUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StudyUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StudyUpdate} obj Optional instance to populate.
     * @return {module:model/StudyUpdate} The populated <code>StudyUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudyUpdate();

            if (data.hasOwnProperty('studyTitle')) {
                obj['studyTitle'] = ApiClient.convertToType(data['studyTitle'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StudyUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StudyUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['studyTitle'] && !(typeof data['studyTitle'] === 'string' || data['studyTitle'] instanceof String)) {
            throw new Error("Expected the field `studyTitle` to be a primitive type in the JSON string but got " + data['studyTitle']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} studyTitle
 */
StudyUpdate.prototype['studyTitle'] = undefined;

/**
 * @member {String} method
 */
StudyUpdate.prototype['method'] = undefined;

/**
 * @member {Number} participants
 */
StudyUpdate.prototype['participants'] = undefined;

/**
 * @member {module:model/StudyUpdate.StatusEnum} status
 */
StudyUpdate.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
StudyUpdate['StatusEnum'] = {

    /**
     * value: "Active"
     * @const
     */
    "Active": "Active",

    /**
     * value: "Planned"
     * @const
     */
    "Planned": "Planned",

    /**
     * value: "Done"
     * @const
     */
    "Done": "Done"
};



export default StudyUpdate;

