/**
 * UX Research Study Tracker API
 * API for managing UX research studies
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Study model module.
 * @module model/Study
 * @version 1.0.0
 */
class Study {
    /**
     * Constructs a new <code>Study</code>.
     * @alias module:model/Study
     * @param id {String} 
     * @param studyTitle {String} 
     * @param method {module:model/Study.MethodEnum} 
     * @param participants {Number} 
     */
    constructor(id, studyTitle, method, participants) { 
        
        Study.initialize(this, id, studyTitle, method, participants);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, studyTitle, method, participants) { 
        obj['id'] = id;
        obj['studyTitle'] = studyTitle;
        obj['method'] = method;
        obj['participants'] = participants;
    }

    /**
     * Constructs a <code>Study</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Study} obj Optional instance to populate.
     * @return {module:model/Study} The populated <code>Study</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Study();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('studyTitle')) {
                obj['studyTitle'] = ApiClient.convertToType(data['studyTitle'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Study</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Study</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Study.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['studyTitle'] && !(typeof data['studyTitle'] === 'string' || data['studyTitle'] instanceof String)) {
            throw new Error("Expected the field `studyTitle` to be a primitive type in the JSON string but got " + data['studyTitle']);
        }
        // ensure the json data is a string
        if (data['method'] && !(typeof data['method'] === 'string' || data['method'] instanceof String)) {
            throw new Error("Expected the field `method` to be a primitive type in the JSON string but got " + data['method']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

Study.RequiredProperties = ["id", "studyTitle", "method", "participants"];

/**
 * @member {String} id
 */
Study.prototype['id'] = undefined;

/**
 * @member {String} studyTitle
 */
Study.prototype['studyTitle'] = undefined;

/**
 * @member {module:model/Study.MethodEnum} method
 */
Study.prototype['method'] = undefined;

/**
 * @member {Number} participants
 */
Study.prototype['participants'] = undefined;

/**
 * @member {module:model/Study.StatusEnum} status
 */
Study.prototype['status'] = undefined;





/**
 * Allowed values for the <code>method</code> property.
 * @enum {String}
 * @readonly
 */
Study['MethodEnum'] = {

    /**
     * value: "Interview"
     * @const
     */
    "Interview": "Interview",

    /**
     * value: "Survey"
     * @const
     */
    "Survey": "Survey",

    /**
     * value: "UsabilityTest"
     * @const
     */
    "UsabilityTest": "UsabilityTest"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Study['StatusEnum'] = {

    /**
     * value: "Active"
     * @const
     */
    "Active": "Active",

    /**
     * value: "Planned"
     * @const
     */
    "Planned": "Planned",

    /**
     * value: "Done"
     * @const
     */
    "Done": "Done"
};



export default Study;

