/**
 * UX Research Study Tracker API
 * API for managing UX research studies
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UxResearchStudyTrackerApi);
  }
}(this, function(expect, UxResearchStudyTrackerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UxResearchStudyTrackerApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('studyServiceActive', function() {
      it('should call studyServiceActive successfully', function(done) {
        //uncomment below and update the code to test studyServiceActive
        //instance.studyServiceActive(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('studyServiceCreate', function() {
      it('should call studyServiceCreate successfully', function(done) {
        //uncomment below and update the code to test studyServiceCreate
        //instance.studyServiceCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('studyServiceDelete', function() {
      it('should call studyServiceDelete successfully', function(done) {
        //uncomment below and update the code to test studyServiceDelete
        //instance.studyServiceDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('studyServiceGet', function() {
      it('should call studyServiceGet successfully', function(done) {
        //uncomment below and update the code to test studyServiceGet
        //instance.studyServiceGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('studyServiceList', function() {
      it('should call studyServiceList successfully', function(done) {
        //uncomment below and update the code to test studyServiceList
        //instance.studyServiceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('studyServiceUpdate', function() {
      it('should call studyServiceUpdate successfully', function(done) {
        //uncomment below and update the code to test studyServiceUpdate
        //instance.studyServiceUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
